### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jappleba** [learn-co-curriculum/sinatra-nested-forms-lab-superheros#18]
The github link does not work. I forked and cloned from the raise issue link. The tests are not linked to learn. I completed and passed but Learn does not recognize any connection.

**Comment by NoneOfMaster** [comment]
I also had to come here to find the lab. 'View on GitHub' and 'Fork' links are 404s.

**Comment by AnnJohn** [comment]
Thanks @jappleba and @NoneOfMaster. We're fixing this right now.
