### ISSUE TITLE
environment.rb suggestion

### ISSUE THREAD

**Issue by dslivken** [learn-co-curriculum/sinatra-nested-forms-lab-superheros#25]
Note - disregard - I understand why I was having a problem earlier. I didn't realize an application controller had already been started (I had tried to create my own app.rb file the way things had been structured in previous labs)

Hi there - just a suggestion, I don't know if it was intended to be part of the challenge of this lab, but I am using the Learn IDE and could not get anything to work at all until I changed the following in the environment.rb file
from: require_all 'app'
to: require './app'

This was not easily identified as a problem via error messaging and was really frustrating given I couldn't even get "get '/' do..." to work after so many other labs. I tried the above change based on comparing the environment file in this lab to the environment files in other labs.

David

**Comment by gj** [comment]
Glad you figured it out, @dslivken! 🙂
