### ISSUE TITLE
Unclear how to set `erb:` to look in `app/views`

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/sinatra-nested-forms-lab-superheros#26]
A student pointed out that it was a bit unclear as to how to setup a sinatra app to look into `app/views` for the view rather than `app/controllers/views`.

The solution uses `set :views, Proc.new { File.join(root, "../views/") }` in the controller.
https://github.com/learn-co-curriculum/sinatra-nested-forms-lab-superheros/blob/solution/app/controllers/application_controller.rb#L5

Maybe we can add a hint for this somewhere? Or do we feel students should be able to figure this out on their own?

@cernanb @gj

**Comment by gj** [comment]
Adding a hint to the README, but just to clarify the student wants to tell Sinatra to look in `app/views` instead of `views`; not `app/controllers/views`, right? A top-level `views` directory is the Sinatra default.

**Comment by gj** [comment]
How does this look? https://github.com/learn-co-curriculum/sinatra-nested-forms-lab-superheros/commit/43f4c521dc88aa67442218ab788fe6c3369f7996

@aturkewi

**Comment by aturkewi** [comment]
Looks great! Thanks so much :)
And for some reason, I think the student's default was looking in `app/controllers/views`. No idea why it was looking there. Didn't dig, just directed them to how to solve.
