### ISSUE TITLE
Learn IDE issues?

### ISSUE THREAD

**Issue by infopro94** [learn-co-curriculum/sinatra-nested-forms-lab-superheros#27]
FYI - Daniel & I solved the problem of my lab, had all the tests passing then Learn IDE wouldn't let me submit it. I did another pull and the system threw a lot of garbage (======HEAD and other, more bizarre code) into my code. I cleaned it up as best I could and started getting an error message (
  1) App POST /teams submits the form
     Failure/Error: expect(page).to have_text("Hero Power: JavaScript")
       expected #has_text?("Hero Power: JavaScript") to return true, got false
     # ./spec/super_sinatra_forms_spec.rb:40:in `block (3 levels) in <top (required)>') that we had resolved earlier. 
Earlier today I had to reconnect Learn IDE because it wouldn't respond to Ctrl+C when I tried to get out of shotgun. Hope this is a temporary glitch!

**Comment by sgharms** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
