### ISSUE TITLE
Syntactic Errors with "spec/super_sinatra_forms_spec.rb"

### ISSUE THREAD

**Issue by jokerdelta** [learn-co-curriculum/sinatra-nested-forms-lab-superheros#28]
Guys, I think there's a couple of issues with RSPEC in this lesson.  Despite my code working well (and making sure to use the naming conventions specified for Capybara) I can't get it to pass and I keep getting syntax error messages for RSPEC.  I found a couple of things in the "spec/super_sinatra_forms_spec" but even after correcting them I couldn't get my tests to pass:

Line 1 should be :  describe "App" do     it's missing the quotation marks around the class name "App".
Line 3 should be :  describe "GET'/' " do  the quotation marks are misplaced.

The only thing I could find was the following line was missing from the spec_helper file:
require 'capybara/dsl' 

I'm still receiving the following errors related to RSPEC but need to move on to my next assignment sorry and it's still a bit over my head. Hope this helps :)

Failures:
  1) App GET '/' returns a 200 status code
     Failure/Error: get '/'
     NoMethodError:
       undefined method `get' for #<RSpec::ExampleGroups::App::GET:0x00000001bab408>
       Did you mean?  gets
                      gem
     # ./spec/super_sinatra_forms_spec.rb:5:in `block (3 levels) in <top (required)>'
  2) App GET '/' renders super hero form
     Failure/Error: get '/'
     NoMethodError:
       undefined method `get' for #<RSpec::ExampleGroups::App::GET:0x00000001ba9d60>
       Did you mean?  gets
                      gem
     # ./spec/super_sinatra_forms_spec.rb:5:in `block (3 levels) in <top (required)>'
  3) App POST /teams submits the form
     Failure/Error: visit '/'
     NoMethodError:
       undefined method `visit' for #<RSpec::ExampleGroups::App::POSTTeams:0x00000001b9ff18>
     # ./spec/super_sinatra_forms_spec.rb:21:in `block (3 levels) in <top (required)>'

Looks like in the slack channel other folks are having the same issue..

**Comment by sgharms** [comment]
I just attempted this code and was able to get it working without making these suggested changes. Judging by the errors it seems to be something along the lines of your rspec version not having loaded to helper methods you need. You may need some help debugging this via Ask A Question.

If, after reviewing your code and consulting AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
