### ISSUE TITLE
Specification of Sinatra gem 1.4.3 is breaking click_button Capybara test

### ISSUE THREAD

**Issue by tgray017** [learn-co-curriculum/sinatra-nested-forms-lab-superheros#31]
I'm getting the following error running the test suite:
`  1) App POST /teams submits the form
     Failure/Error: click_button 'submit'
     NoMethodError:
       undefined method 'join' for #<String:0x00000000041ce040>
`

I added `value="submit"` and  `id="submit"` to the html but still no luck in getting Capybara to successfully click the button. 

Removing the 1.4.3 version specification for the sinatra gem and running `bundle update` solves the issue.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
