### ISSUE TITLE
Third test 

### ISSUE THREAD

**Issue by reevesalic** [learn-co-curriculum/sinatra-nested-forms-lab-superheros#36]
I had the technician assist me and we were not able to figure out why the 3rd test would not pass. I was able to submit my form and the information displayed on the site.

**Comment by lizbur10** [comment]
Hi Alicia! I took a look and it looks like you needed a capital "p" in "Hero power".  

I'm going to close this issue but please feel free to reopen it if you still believe there's a problem with the test.

Thanks for contributing!
